apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app3-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 3</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
                color: white;
            }
            .container {
                text-align: center;
            }
            h1 {
                font-size: 4em;
                margin: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🌟 Application 3</h1>
            <p>Hello from default app</p>
            <p><small>(Default fallback)</small></p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: app3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
