Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "luqmanS" do |srv|
    srv.vm.hostname = "luqmanS"
    srv.vm.network "private_network", ip: "192.168.56.110", netmask: "255.255.255.0"
    srv.vm.provider "parallels" do |prl|
      prl.name   = "luqmanS"
      prl.memory = 2048
      prl.cpus   = 2
    end
    srv.vm.provision "shell", path: "scripts/setup.sh"
  end
end
