apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-chat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TON_USERNAME_GITHUB/iot-deployment.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
