#!/usr/bin/env bash
set -euo pipefail

echo "=== Configuration de GitLab ==="

GITLAB_URL="http://localhost:8081"
GITLAB_PASSWORD=$(cat scripts/gitlab_root_password.txt)
PROJECT_NAME="iot-deployment"

echo ""
echo "Ce script nécessite des étapes manuelles."
echo ""
echo "============================================"
echo "ÉTAPES À SUIVRE MANUELLEMENT:"
echo "============================================"
echo ""
echo "1. Ouvrir GitLab: ${GITLAB_URL}"
echo "2. Se connecter:"
echo "   - Username: root"
echo "   - Password: ${GITLAB_PASSWORD}"
echo ""
echo "3. Créer un nouveau projet:"
echo "   - Cliquer sur 'New project'"
echo "   - Choisir 'Create blank project'"
echo "   - Project name: ${PROJECT_NAME}"
echo "   - Visibility: Public"
echo "   - Décocher 'Initialize repository with a README'"
echo "   - Cliquer sur 'Create project'"
echo ""
echo "4. Créer un Personal Access Token:"
echo "   - Aller dans: User Settings > Access Tokens"
echo "   - Token name: argocd"
echo "   - Expiration: Pas d'expiration"
echo "   - Scopes: cocher 'api' et 'read_repository'"
echo "   - Cliquer sur 'Create personal access token'"
echo "   - COPIER LE TOKEN (vous ne le reverrez plus!)"
echo ""
echo "5. Sauvegarder le token:"
echo "   - Créer le fichier: scripts/gitlab_token.txt"
echo "   - Y coller le token"
echo ""
echo "6. Pousser le code vers GitLab:"
echo "   cd confs/"
echo "   git init"
echo "   git remote add origin http://localhost:8081/root/${PROJECT_NAME}.git"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git push -u origin main"
echo ""
echo "   (Username: root, Password: ${GITLAB_PASSWORD})"
echo ""
echo "============================================"
echo ""
echo "Une fois terminé, exécuter:"
echo "  ./scripts/04_setup_argocd.sh"
echo "============================================"