Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Désactiver le démarrage parallèle
  ENV['VAGRANT_NO_PARALLEL'] = 'yes'

  # ===== Server =====
  config.vm.define "luqmanS", primary: true do |srv|
    srv.vm.hostname = "luqmanS"
    srv.vm.network "private_network", ip: "192.168.56.110"
    srv.vm.provider "parallels" do |prl|
      prl.name   = "luqmanS"
      prl.memory = 1024
      prl.cpus   = 1
    end
    srv.vm.provision "shell", path: "scripts/install_k3s_server.sh"
    srv.vm.provision "shell", inline: <<-SHELL
      echo "Attente que K3s soit prêt..."
      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do
        sleep 2
      done
      sleep 10
      echo "Serveur K3s prêt!"
    SHELL
  end

  # ===== Worker =====
  config.vm.define "luqmanSW" do |wrk|
    wrk.vm.hostname = "luqmanSW"
    wrk.vm.network "private_network", ip: "192.168.56.111"
    wrk.vm.provider "parallels" do |prl|
      prl.name   = "luqmanSW"
      prl.memory = 1024
      prl.cpus   = 1
    end
    wrk.vm.provision "shell", path: "scripts/install_k3s_worker.sh"
  end
end